name: Trivy Scan
description: Scan container image with Trivy
inputs:
  image:
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@d2472f4cfe2bfe3bc99e7cfc9a6c4c2df6dd3b15 # v0.35.0
      with:
        image-ref: ${{ inputs.image }}
        format: "table"
        severity: "HIGH,CRITICAL"
