# Copyright 2025 The llm-d Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tokenizerpb import tokenizer_pb2 as tokenizerpb_dot_tokenizer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tokenizerpb/tokenizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TokenizationServiceStub(object):
    """TokenizationService defines the gRPC service for tokenization
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tokenize = channel.unary_unary(
                '/tokenization.TokenizationService/Tokenize',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.FromString,
                _registered_method=True)
        self.RenderChatTemplate = channel.unary_unary(
                '/tokenization.TokenizationService/RenderChatTemplate',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateResponse.FromString,
                _registered_method=True)
        self.InitializeTokenizer = channel.unary_unary(
                '/tokenization.TokenizationService/InitializeTokenizer',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerResponse.FromString,
                _registered_method=True)
        self.RenderChatCompletion = channel.unary_unary(
                '/tokenization.TokenizationService/RenderChatCompletion',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.RenderChatCompletionRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.RenderChatCompletionResponse.FromString,
                _registered_method=True)
        self.RenderCompletion = channel.unary_unary(
                '/tokenization.TokenizationService/RenderCompletion',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.RenderCompletionRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.RenderCompletionResponse.FromString,
                _registered_method=True)


class TokenizationServiceServicer(object):
    """TokenizationService defines the gRPC service for tokenization
    """

    def Tokenize(self, request, context):
        """Tokenize converts a text input to token IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderChatTemplate(self, request, context):
        """Deprecated: use RenderChatCompletion instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeTokenizer(self, request, context):
        """InitializeTokenizer initializes the tokenizer for a specific model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderChatCompletion(self, request, context):
        """RenderChatCompletion renders an OpenAI chat completion request via OpenAIServingRender,
        returning token IDs and multimodal features as a GenerateRequest-compatible response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderCompletion(self, request, context):
        """RenderCompletion renders an OpenAI completion request via OpenAIServingRender,
        returning the rendered output for the given prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TokenizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.TokenizeRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.SerializeToString,
            ),
            'RenderChatTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderChatTemplate,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateResponse.SerializeToString,
            ),
            'InitializeTokenizer': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeTokenizer,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerResponse.SerializeToString,
            ),
            'RenderChatCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderChatCompletion,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.RenderChatCompletionRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.RenderChatCompletionResponse.SerializeToString,
            ),
            'RenderCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderCompletion,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.RenderCompletionRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.RenderCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tokenization.TokenizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tokenization.TokenizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TokenizationService(object):
    """TokenizationService defines the gRPC service for tokenization
    """

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/Tokenize',
            tokenizerpb_dot_tokenizer__pb2.TokenizeRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderChatTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/RenderChatTemplate',
            tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.ChatTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeTokenizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/InitializeTokenizer',
            tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/RenderChatCompletion',
            tokenizerpb_dot_tokenizer__pb2.RenderChatCompletionRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.RenderChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/RenderCompletion',
            tokenizerpb_dot_tokenizer__pb2.RenderCompletionRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.RenderCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
