// Copyright 2025 The llm-d Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/tokenizerpb/tokenizer.proto

package tokenizerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenizeRequest represents a request to tokenize a text input
type TokenizeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Input            string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`                                                  // The text input to tokenize
	ModelName        string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                         // The name of the model to use for tokenization
	AddSpecialTokens bool                   `protobuf:"varint,3,opt,name=add_special_tokens,json=addSpecialTokens,proto3" json:"add_special_tokens,omitempty"` // Whether to add special tokens during tokenization
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenizeRequest) Reset() {
	*x = TokenizeRequest{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizeRequest) ProtoMessage() {}

func (x *TokenizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizeRequest.ProtoReflect.Descriptor instead.
func (*TokenizeRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{0}
}

func (x *TokenizeRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TokenizeRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *TokenizeRequest) GetAddSpecialTokens() bool {
	if x != nil {
		return x.AddSpecialTokens
	}
	return false
}

// TokenizeResponse represents the response from tokenization
type TokenizeResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InputIds     []uint32               `protobuf:"varint,1,rep,packed,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`     // Token IDs for the input
	Success      bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                              // Whether the request was successful
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if the request failed
	// Direct array of [start, end] pairs
	OffsetPairs   []uint32 `protobuf:"varint,4,rep,packed,name=offset_pairs,json=offsetPairs,proto3" json:"offset_pairs,omitempty"` // Flattened array of [start, end, start, end, ...]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenizeResponse) Reset() {
	*x = TokenizeResponse{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenizeResponse) ProtoMessage() {}

func (x *TokenizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenizeResponse.ProtoReflect.Descriptor instead.
func (*TokenizeResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{1}
}

func (x *TokenizeResponse) GetInputIds() []uint32 {
	if x != nil {
		return x.InputIds
	}
	return nil
}

func (x *TokenizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TokenizeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TokenizeResponse) GetOffsetPairs() []uint32 {
	if x != nil {
		return x.OffsetPairs
	}
	return nil
}

// ConversationTurn represents a single turn in a conversation (a single message or multiple messages per turn)
type ConversationTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // The messages in this turn
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationTurn) Reset() {
	*x = ConversationTurn{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTurn) ProtoMessage() {}

func (x *ConversationTurn) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTurn.ProtoReflect.Descriptor instead.
func (*ConversationTurn) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{2}
}

func (x *ConversationTurn) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// ChatTemplateRequest represents a request to render a chat template
type ChatTemplateRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ConversationTurns         []*ConversationTurn    `protobuf:"bytes,1,rep,name=conversation_turns,json=conversationTurns,proto3" json:"conversation_turns,omitempty"`                                                                                // The conversation turns (batches of messages)
	Tools                     []*ToolDescription     `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`                                                                                                                                 // Tools available to the conversation
	Documents                 []*Document            `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`                                                                                                                         // Documents related to the conversation
	ChatTemplate              string                 `protobuf:"bytes,4,opt,name=chat_template,json=chatTemplate,proto3" json:"chat_template,omitempty"`                                                                                               // The chat template to use
	ReturnAssistantTokensMask bool                   `protobuf:"varint,5,opt,name=return_assistant_tokens_mask,json=returnAssistantTokensMask,proto3" json:"return_assistant_tokens_mask,omitempty"`                                                   // Whether to return assistant token mask
	ContinueFinalMessage      bool                   `protobuf:"varint,6,opt,name=continue_final_message,json=continueFinalMessage,proto3" json:"continue_final_message,omitempty"`                                                                    // Whether to continue the final message
	AddGenerationPrompt       bool                   `protobuf:"varint,7,opt,name=add_generation_prompt,json=addGenerationPrompt,proto3" json:"add_generation_prompt,omitempty"`                                                                       // Whether to add generation prompt
	ChatTemplateKwargs        map[string]*Value      `protobuf:"bytes,8,rep,name=chat_template_kwargs,json=chatTemplateKwargs,proto3" json:"chat_template_kwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional chat template arguments
	ModelName                 string                 `protobuf:"bytes,9,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                                                                                        // The name of the model to use for tokenization
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ChatTemplateRequest) Reset() {
	*x = ChatTemplateRequest{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTemplateRequest) ProtoMessage() {}

func (x *ChatTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTemplateRequest.ProtoReflect.Descriptor instead.
func (*ChatTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{3}
}

func (x *ChatTemplateRequest) GetConversationTurns() []*ConversationTurn {
	if x != nil {
		return x.ConversationTurns
	}
	return nil
}

func (x *ChatTemplateRequest) GetTools() []*ToolDescription {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatTemplateRequest) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ChatTemplateRequest) GetChatTemplate() string {
	if x != nil {
		return x.ChatTemplate
	}
	return ""
}

func (x *ChatTemplateRequest) GetReturnAssistantTokensMask() bool {
	if x != nil {
		return x.ReturnAssistantTokensMask
	}
	return false
}

func (x *ChatTemplateRequest) GetContinueFinalMessage() bool {
	if x != nil {
		return x.ContinueFinalMessage
	}
	return false
}

func (x *ChatTemplateRequest) GetAddGenerationPrompt() bool {
	if x != nil {
		return x.AddGenerationPrompt
	}
	return false
}

func (x *ChatTemplateRequest) GetChatTemplateKwargs() map[string]*Value {
	if x != nil {
		return x.ChatTemplateKwargs
	}
	return nil
}

func (x *ChatTemplateRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

// ImageUrl represents the image_url content block field
type ImageUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // URL of the image (http/https or data URI)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUrl) Reset() {
	*x = ImageUrl{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUrl) ProtoMessage() {}

func (x *ImageUrl) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUrl.ProtoReflect.Descriptor instead.
func (*ImageUrl) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{4}
}

func (x *ImageUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ContentPart represents a single part of a multimodal message content block
type ContentPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                               // "text" or "image_url"
	Text          *string                `protobuf:"bytes,2,opt,name=text,proto3,oneof" json:"text,omitempty"`                         // Text content (type == "text")
	ImageUrl      *ImageUrl              `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"` // Image content (type == "image_url")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPart) Reset() {
	*x = ContentPart{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPart) ProtoMessage() {}

func (x *ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPart.ProtoReflect.Descriptor instead.
func (*ContentPart) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{5}
}

func (x *ContentPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentPart) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *ContentPart) GetImageUrl() *ImageUrl {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

// ChatMessage represents a single message in a conversation.
// Mirrors Content in pkg/tokenization/types: set content for plain text,
// content_parts for multimodal (image_url blocks). Exactly one should be set.
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`                                     // Role of the message (e.g., "user", "assistant", "system")
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`                         // Plain-text content (Content.Raw)
	ContentParts  []*ContentPart         `protobuf:"bytes,3,rep,name=content_parts,json=contentParts,proto3" json:"content_parts,omitempty"` // Multimodal content blocks (Content.Structured)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *ChatMessage) GetContentParts() []*ContentPart {
	if x != nil {
		return x.ContentParts
	}
	return nil
}

// ToolDescription represents a description of a tool
type ToolDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          map[string]*Value      `protobuf:"bytes,1,rep,name=tool,proto3" json:"tool,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Tool definition
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDescription) Reset() {
	*x = ToolDescription{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDescription) ProtoMessage() {}

func (x *ToolDescription) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDescription.ProtoReflect.Descriptor instead.
func (*ToolDescription) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{7}
}

func (x *ToolDescription) GetTool() map[string]*Value {
	if x != nil {
		return x.Tool
	}
	return nil
}

// Document represents a document
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      map[string]*Value      `protobuf:"bytes,1,rep,name=document,proto3" json:"document,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Document definition
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{8}
}

func (x *Document) GetDocument() map[string]*Value {
	if x != nil {
		return x.Document
	}
	return nil
}

// Value represents a generic value that can be string, number, bool, or list
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_NumberValue
	//	*Value_BoolValue
	//	*Value_ListValue
	//	*Value_StructValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{9}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetStructValue() *StructValue {
	if x != nil {
		if x, ok := x.Value.(*Value_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,4,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_StructValue struct {
	StructValue *StructValue `protobuf:"bytes,5,opt,name=struct_value,json=structValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_NumberValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_ListValue) isValue_Value() {}

func (*Value_StructValue) isValue_Value() {}

// ListValue represents a list of values
type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{10}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// StructValue represents a structured value (key-value pairs)
type StructValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructValue) Reset() {
	*x = StructValue{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructValue) ProtoMessage() {}

func (x *StructValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructValue.ProtoReflect.Descriptor instead.
func (*StructValue) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{11}
}

func (x *StructValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ChatTemplateResponse represents the response from rendering a chat template
type ChatTemplateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RenderedPrompt string                 `protobuf:"bytes,1,opt,name=rendered_prompt,json=renderedPrompt,proto3" json:"rendered_prompt,omitempty"` // The rendered chat template prompt
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                                    // Whether the request was successful
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`       // Error message if the request failed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatTemplateResponse) Reset() {
	*x = ChatTemplateResponse{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTemplateResponse) ProtoMessage() {}

func (x *ChatTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTemplateResponse.ProtoReflect.Descriptor instead.
func (*ChatTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{12}
}

func (x *ChatTemplateResponse) GetRenderedPrompt() string {
	if x != nil {
		return x.RenderedPrompt
	}
	return ""
}

func (x *ChatTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChatTemplateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// InitializeTokenizerRequest represents a request to initialize tokenizer for a model
type InitializeTokenizerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ModelName           string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                  // The name of the model to initialize
	EnableThinking      bool                   `protobuf:"varint,2,opt,name=enable_thinking,json=enableThinking,proto3" json:"enable_thinking,omitempty"`                  // Whether to enable thinking tokens
	AddGenerationPrompt bool                   `protobuf:"varint,3,opt,name=add_generation_prompt,json=addGenerationPrompt,proto3" json:"add_generation_prompt,omitempty"` // Whether to add generation prompt
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InitializeTokenizerRequest) Reset() {
	*x = InitializeTokenizerRequest{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeTokenizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeTokenizerRequest) ProtoMessage() {}

func (x *InitializeTokenizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeTokenizerRequest.ProtoReflect.Descriptor instead.
func (*InitializeTokenizerRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{13}
}

func (x *InitializeTokenizerRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *InitializeTokenizerRequest) GetEnableThinking() bool {
	if x != nil {
		return x.EnableThinking
	}
	return false
}

func (x *InitializeTokenizerRequest) GetAddGenerationPrompt() bool {
	if x != nil {
		return x.AddGenerationPrompt
	}
	return false
}

// InitializeTokenizerResponse represents the response from tokenizer initialization
type InitializeTokenizerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Whether the initialization was successful
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if initialization failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeTokenizerResponse) Reset() {
	*x = InitializeTokenizerResponse{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeTokenizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeTokenizerResponse) ProtoMessage() {}

func (x *InitializeTokenizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeTokenizerResponse.ProtoReflect.Descriptor instead.
func (*InitializeTokenizerResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{14}
}

func (x *InitializeTokenizerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeTokenizerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// PlaceholderRange represents a range of placeholder tokens for a multimodal item
type PlaceholderRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // Start index of the placeholder tokens in the prompt
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"` // Number of placeholder tokens
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceholderRange) Reset() {
	*x = PlaceholderRange{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceholderRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceholderRange) ProtoMessage() {}

func (x *PlaceholderRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceholderRange.ProtoReflect.Descriptor instead.
func (*PlaceholderRange) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{15}
}

func (x *PlaceholderRange) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PlaceholderRange) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// StringList holds a list of strings (used as map values)
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{16}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// PlaceholderRangeList holds a list of PlaceholderRange (used as map values)
type PlaceholderRangeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranges        []*PlaceholderRange    `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceholderRangeList) Reset() {
	*x = PlaceholderRangeList{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceholderRangeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceholderRangeList) ProtoMessage() {}

func (x *PlaceholderRangeList) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceholderRangeList.ProtoReflect.Descriptor instead.
func (*PlaceholderRangeList) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{17}
}

func (x *PlaceholderRangeList) GetRanges() []*PlaceholderRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// MultiModalFeatures contains multimodal metadata produced by the render step
type MultiModalFeatures struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	MmHashes       map[string]*StringList           `protobuf:"bytes,1,rep,name=mm_hashes,json=mmHashes,proto3" json:"mm_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                   // Per-modality item hashes
	MmPlaceholders map[string]*PlaceholderRangeList `protobuf:"bytes,2,rep,name=mm_placeholders,json=mmPlaceholders,proto3" json:"mm_placeholders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Per-modality placeholder ranges
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultiModalFeatures) Reset() {
	*x = MultiModalFeatures{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiModalFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiModalFeatures) ProtoMessage() {}

func (x *MultiModalFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiModalFeatures.ProtoReflect.Descriptor instead.
func (*MultiModalFeatures) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{18}
}

func (x *MultiModalFeatures) GetMmHashes() map[string]*StringList {
	if x != nil {
		return x.MmHashes
	}
	return nil
}

func (x *MultiModalFeatures) GetMmPlaceholders() map[string]*PlaceholderRangeList {
	if x != nil {
		return x.MmPlaceholders
	}
	return nil
}

// RenderChatCompletionRequest contains the fields from an OpenAI chat completion
// request that are relevant to rendering (chat template application + tokenization).
type RenderChatCompletionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ModelName            string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                        // Model name to use for renderer selection
	Messages             []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`                                                           // Conversation messages
	ToolsJson            *string                `protobuf:"bytes,3,opt,name=tools_json,json=toolsJson,proto3,oneof" json:"tools_json,omitempty"`                                  // Tools available to the model, as a JSON array
	ChatTemplate         string                 `protobuf:"bytes,4,opt,name=chat_template,json=chatTemplate,proto3" json:"chat_template,omitempty"`                               // Override chat template (optional)
	AddGenerationPrompt  *bool                  `protobuf:"varint,5,opt,name=add_generation_prompt,json=addGenerationPrompt,proto3,oneof" json:"add_generation_prompt,omitempty"` // Whether to append the generation prompt (default: true)
	ContinueFinalMessage bool                   `protobuf:"varint,6,opt,name=continue_final_message,json=continueFinalMessage,proto3" json:"continue_final_message,omitempty"`    // Whether to continue the final message
	ChatTemplateKwargs   *string                `protobuf:"bytes,7,opt,name=chat_template_kwargs,json=chatTemplateKwargs,proto3,oneof" json:"chat_template_kwargs,omitempty"`     // Additional chat template arguments as JSON
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RenderChatCompletionRequest) Reset() {
	*x = RenderChatCompletionRequest{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderChatCompletionRequest) ProtoMessage() {}

func (x *RenderChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*RenderChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{19}
}

func (x *RenderChatCompletionRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RenderChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *RenderChatCompletionRequest) GetToolsJson() string {
	if x != nil && x.ToolsJson != nil {
		return *x.ToolsJson
	}
	return ""
}

func (x *RenderChatCompletionRequest) GetChatTemplate() string {
	if x != nil {
		return x.ChatTemplate
	}
	return ""
}

func (x *RenderChatCompletionRequest) GetAddGenerationPrompt() bool {
	if x != nil && x.AddGenerationPrompt != nil {
		return *x.AddGenerationPrompt
	}
	return false
}

func (x *RenderChatCompletionRequest) GetContinueFinalMessage() bool {
	if x != nil {
		return x.ContinueFinalMessage
	}
	return false
}

func (x *RenderChatCompletionRequest) GetChatTemplateKwargs() string {
	if x != nil && x.ChatTemplateKwargs != nil {
		return *x.ChatTemplateKwargs
	}
	return ""
}

// RenderChatCompletionResponse contains the rendered output from OpenAIServingRender
type RenderChatCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`          // Request ID from the render response
	TokenIds      []uint32               `protobuf:"varint,2,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`     // Token IDs for the rendered input
	Features      *MultiModalFeatures    `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`                             // Multimodal features (populated for MM inputs)
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`                              // Whether the request was successful
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if the request failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderChatCompletionResponse) Reset() {
	*x = RenderChatCompletionResponse{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderChatCompletionResponse) ProtoMessage() {}

func (x *RenderChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*RenderChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{20}
}

func (x *RenderChatCompletionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenderChatCompletionResponse) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *RenderChatCompletionResponse) GetFeatures() *MultiModalFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *RenderChatCompletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenderChatCompletionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RenderCompletionRequest contains the fields from an OpenAI completion request
// that are relevant to rendering (validation + tokenization).
type RenderCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"` // Model name to use for renderer selection
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`                        // Text prompt to render
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderCompletionRequest) Reset() {
	*x = RenderCompletionRequest{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderCompletionRequest) ProtoMessage() {}

func (x *RenderCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderCompletionRequest.ProtoReflect.Descriptor instead.
func (*RenderCompletionRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{21}
}

func (x *RenderCompletionRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RenderCompletionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// RenderCompletionResponse contains the rendered output for a completion request.
type RenderCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`          // Request ID from the render response
	TokenIds      []uint32               `protobuf:"varint,2,rep,packed,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`     // Token IDs for the rendered prompt
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                              // Whether the request was successful
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if the request failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderCompletionResponse) Reset() {
	*x = RenderCompletionResponse{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderCompletionResponse) ProtoMessage() {}

func (x *RenderCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderCompletionResponse.ProtoReflect.Descriptor instead.
func (*RenderCompletionResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{22}
}

func (x *RenderCompletionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenderCompletionResponse) GetTokenIds() []uint32 {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *RenderCompletionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenderCompletionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_tokenizerpb_tokenizer_proto protoreflect.FileDescriptor

const file_api_tokenizerpb_tokenizer_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/tokenizerpb/tokenizer.proto\x12\ftokenization\"t\n" +
	"\x0fTokenizeRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12,\n" +
	"\x12add_special_tokens\x18\x03 \x01(\bR\x10addSpecialTokens\"\x91\x01\n" +
	"\x10TokenizeResponse\x12\x1b\n" +
	"\tinput_ids\x18\x01 \x03(\rR\binputIds\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12!\n" +
	"\foffset_pairs\x18\x04 \x03(\rR\voffsetPairs\"I\n" +
	"\x10ConversationTurn\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.tokenization.ChatMessageR\bmessages\"\x87\x05\n" +
	"\x13ChatTemplateRequest\x12M\n" +
	"\x12conversation_turns\x18\x01 \x03(\v2\x1e.tokenization.ConversationTurnR\x11conversationTurns\x123\n" +
	"\x05tools\x18\x02 \x03(\v2\x1d.tokenization.ToolDescriptionR\x05tools\x124\n" +
	"\tdocuments\x18\x03 \x03(\v2\x16.tokenization.DocumentR\tdocuments\x12#\n" +
	"\rchat_template\x18\x04 \x01(\tR\fchatTemplate\x12?\n" +
	"\x1creturn_assistant_tokens_mask\x18\x05 \x01(\bR\x19returnAssistantTokensMask\x124\n" +
	"\x16continue_final_message\x18\x06 \x01(\bR\x14continueFinalMessage\x122\n" +
	"\x15add_generation_prompt\x18\a \x01(\bR\x13addGenerationPrompt\x12k\n" +
	"\x14chat_template_kwargs\x18\b \x03(\v29.tokenization.ChatTemplateRequest.ChatTemplateKwargsEntryR\x12chatTemplateKwargs\x12\x1d\n" +
	"\n" +
	"model_name\x18\t \x01(\tR\tmodelName\x1aZ\n" +
	"\x17ChatTemplateKwargsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tokenization.ValueR\x05value:\x028\x01\"\x1c\n" +
	"\bImageUrl\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8b\x01\n" +
	"\vContentPart\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x88\x01\x01\x128\n" +
	"\timage_url\x18\x03 \x01(\v2\x16.tokenization.ImageUrlH\x01R\bimageUrl\x88\x01\x01B\a\n" +
	"\x05_textB\f\n" +
	"\n" +
	"_image_url\"\x8c\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x12>\n" +
	"\rcontent_parts\x18\x03 \x03(\v2\x19.tokenization.ContentPartR\fcontentPartsB\n" +
	"\n" +
	"\b_content\"\x9c\x01\n" +
	"\x0fToolDescription\x12;\n" +
	"\x04tool\x18\x01 \x03(\v2'.tokenization.ToolDescription.ToolEntryR\x04tool\x1aL\n" +
	"\tToolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tokenization.ValueR\x05value:\x028\x01\"\x9e\x01\n" +
	"\bDocument\x12@\n" +
	"\bdocument\x18\x01 \x03(\v2$.tokenization.Document.DocumentEntryR\bdocument\x1aP\n" +
	"\rDocumentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tokenization.ValueR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x128\n" +
	"\n" +
	"list_value\x18\x04 \x01(\v2\x17.tokenization.ListValueH\x00R\tlistValue\x12>\n" +
	"\fstruct_value\x18\x05 \x01(\v2\x19.tokenization.StructValueH\x00R\vstructValueB\a\n" +
	"\x05value\"8\n" +
	"\tListValue\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.tokenization.ValueR\x06values\"\x9c\x01\n" +
	"\vStructValue\x12=\n" +
	"\x06fields\x18\x01 \x03(\v2%.tokenization.StructValue.FieldsEntryR\x06fields\x1aN\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tokenization.ValueR\x05value:\x028\x01\"~\n" +
	"\x14ChatTemplateResponse\x12'\n" +
	"\x0frendered_prompt\x18\x01 \x01(\tR\x0erenderedPrompt\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x98\x01\n" +
	"\x1aInitializeTokenizerRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12'\n" +
	"\x0fenable_thinking\x18\x02 \x01(\bR\x0eenableThinking\x122\n" +
	"\x15add_generation_prompt\x18\x03 \x01(\bR\x13addGenerationPrompt\"\\\n" +
	"\x1bInitializeTokenizerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"B\n" +
	"\x10PlaceholderRange\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"N\n" +
	"\x14PlaceholderRangeList\x126\n" +
	"\x06ranges\x18\x01 \x03(\v2\x1e.tokenization.PlaceholderRangeR\x06ranges\"\xfe\x02\n" +
	"\x12MultiModalFeatures\x12K\n" +
	"\tmm_hashes\x18\x01 \x03(\v2..tokenization.MultiModalFeatures.MmHashesEntryR\bmmHashes\x12]\n" +
	"\x0fmm_placeholders\x18\x02 \x03(\v24.tokenization.MultiModalFeatures.MmPlaceholdersEntryR\x0emmPlaceholders\x1aU\n" +
	"\rMmHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.tokenization.StringListR\x05value:\x028\x01\x1ae\n" +
	"\x13MmPlaceholdersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".tokenization.PlaceholderRangeListR\x05value:\x028\x01\"\xa4\x03\n" +
	"\x1bRenderChatCompletionRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x125\n" +
	"\bmessages\x18\x02 \x03(\v2\x19.tokenization.ChatMessageR\bmessages\x12\"\n" +
	"\n" +
	"tools_json\x18\x03 \x01(\tH\x00R\ttoolsJson\x88\x01\x01\x12#\n" +
	"\rchat_template\x18\x04 \x01(\tR\fchatTemplate\x127\n" +
	"\x15add_generation_prompt\x18\x05 \x01(\bH\x01R\x13addGenerationPrompt\x88\x01\x01\x124\n" +
	"\x16continue_final_message\x18\x06 \x01(\bR\x14continueFinalMessage\x125\n" +
	"\x14chat_template_kwargs\x18\a \x01(\tH\x02R\x12chatTemplateKwargs\x88\x01\x01B\r\n" +
	"\v_tools_jsonB\x18\n" +
	"\x16_add_generation_promptB\x17\n" +
	"\x15_chat_template_kwargs\"\xd7\x01\n" +
	"\x1cRenderChatCompletionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttoken_ids\x18\x02 \x03(\rR\btokenIds\x12<\n" +
	"\bfeatures\x18\x03 \x01(\v2 .tokenization.MultiModalFeaturesR\bfeatures\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"P\n" +
	"\x17RenderCompletionRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"\x95\x01\n" +
	"\x18RenderCompletionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttoken_ids\x18\x02 \x03(\rR\btokenIds\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\xfb\x03\n" +
	"\x13TokenizationService\x12I\n" +
	"\bTokenize\x12\x1d.tokenization.TokenizeRequest\x1a\x1e.tokenization.TokenizeResponse\x12[\n" +
	"\x12RenderChatTemplate\x12!.tokenization.ChatTemplateRequest\x1a\".tokenization.ChatTemplateResponse\x12j\n" +
	"\x13InitializeTokenizer\x12(.tokenization.InitializeTokenizerRequest\x1a).tokenization.InitializeTokenizerResponse\x12m\n" +
	"\x14RenderChatCompletion\x12).tokenization.RenderChatCompletionRequest\x1a*.tokenization.RenderChatCompletionResponse\x12a\n" +
	"\x10RenderCompletion\x12%.tokenization.RenderCompletionRequest\x1a&.tokenization.RenderCompletionResponseB=Z;github.com/llm-d/llm-d-kv-cache/api/tokenizerpb;tokenizerpbb\x06proto3"

var (
	file_api_tokenizerpb_tokenizer_proto_rawDescOnce sync.Once
	file_api_tokenizerpb_tokenizer_proto_rawDescData []byte
)

func file_api_tokenizerpb_tokenizer_proto_rawDescGZIP() []byte {
	file_api_tokenizerpb_tokenizer_proto_rawDescOnce.Do(func() {
		file_api_tokenizerpb_tokenizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tokenizerpb_tokenizer_proto_rawDesc), len(file_api_tokenizerpb_tokenizer_proto_rawDesc)))
	})
	return file_api_tokenizerpb_tokenizer_proto_rawDescData
}

var file_api_tokenizerpb_tokenizer_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_tokenizerpb_tokenizer_proto_goTypes = []any{
	(*TokenizeRequest)(nil),              // 0: tokenization.TokenizeRequest
	(*TokenizeResponse)(nil),             // 1: tokenization.TokenizeResponse
	(*ConversationTurn)(nil),             // 2: tokenization.ConversationTurn
	(*ChatTemplateRequest)(nil),          // 3: tokenization.ChatTemplateRequest
	(*ImageUrl)(nil),                     // 4: tokenization.ImageUrl
	(*ContentPart)(nil),                  // 5: tokenization.ContentPart
	(*ChatMessage)(nil),                  // 6: tokenization.ChatMessage
	(*ToolDescription)(nil),              // 7: tokenization.ToolDescription
	(*Document)(nil),                     // 8: tokenization.Document
	(*Value)(nil),                        // 9: tokenization.Value
	(*ListValue)(nil),                    // 10: tokenization.ListValue
	(*StructValue)(nil),                  // 11: tokenization.StructValue
	(*ChatTemplateResponse)(nil),         // 12: tokenization.ChatTemplateResponse
	(*InitializeTokenizerRequest)(nil),   // 13: tokenization.InitializeTokenizerRequest
	(*InitializeTokenizerResponse)(nil),  // 14: tokenization.InitializeTokenizerResponse
	(*PlaceholderRange)(nil),             // 15: tokenization.PlaceholderRange
	(*StringList)(nil),                   // 16: tokenization.StringList
	(*PlaceholderRangeList)(nil),         // 17: tokenization.PlaceholderRangeList
	(*MultiModalFeatures)(nil),           // 18: tokenization.MultiModalFeatures
	(*RenderChatCompletionRequest)(nil),  // 19: tokenization.RenderChatCompletionRequest
	(*RenderChatCompletionResponse)(nil), // 20: tokenization.RenderChatCompletionResponse
	(*RenderCompletionRequest)(nil),      // 21: tokenization.RenderCompletionRequest
	(*RenderCompletionResponse)(nil),     // 22: tokenization.RenderCompletionResponse
	nil,                                  // 23: tokenization.ChatTemplateRequest.ChatTemplateKwargsEntry
	nil,                                  // 24: tokenization.ToolDescription.ToolEntry
	nil,                                  // 25: tokenization.Document.DocumentEntry
	nil,                                  // 26: tokenization.StructValue.FieldsEntry
	nil,                                  // 27: tokenization.MultiModalFeatures.MmHashesEntry
	nil,                                  // 28: tokenization.MultiModalFeatures.MmPlaceholdersEntry
}
var file_api_tokenizerpb_tokenizer_proto_depIdxs = []int32{
	6,  // 0: tokenization.ConversationTurn.messages:type_name -> tokenization.ChatMessage
	2,  // 1: tokenization.ChatTemplateRequest.conversation_turns:type_name -> tokenization.ConversationTurn
	7,  // 2: tokenization.ChatTemplateRequest.tools:type_name -> tokenization.ToolDescription
	8,  // 3: tokenization.ChatTemplateRequest.documents:type_name -> tokenization.Document
	23, // 4: tokenization.ChatTemplateRequest.chat_template_kwargs:type_name -> tokenization.ChatTemplateRequest.ChatTemplateKwargsEntry
	4,  // 5: tokenization.ContentPart.image_url:type_name -> tokenization.ImageUrl
	5,  // 6: tokenization.ChatMessage.content_parts:type_name -> tokenization.ContentPart
	24, // 7: tokenization.ToolDescription.tool:type_name -> tokenization.ToolDescription.ToolEntry
	25, // 8: tokenization.Document.document:type_name -> tokenization.Document.DocumentEntry
	10, // 9: tokenization.Value.list_value:type_name -> tokenization.ListValue
	11, // 10: tokenization.Value.struct_value:type_name -> tokenization.StructValue
	9,  // 11: tokenization.ListValue.values:type_name -> tokenization.Value
	26, // 12: tokenization.StructValue.fields:type_name -> tokenization.StructValue.FieldsEntry
	15, // 13: tokenization.PlaceholderRangeList.ranges:type_name -> tokenization.PlaceholderRange
	27, // 14: tokenization.MultiModalFeatures.mm_hashes:type_name -> tokenization.MultiModalFeatures.MmHashesEntry
	28, // 15: tokenization.MultiModalFeatures.mm_placeholders:type_name -> tokenization.MultiModalFeatures.MmPlaceholdersEntry
	6,  // 16: tokenization.RenderChatCompletionRequest.messages:type_name -> tokenization.ChatMessage
	18, // 17: tokenization.RenderChatCompletionResponse.features:type_name -> tokenization.MultiModalFeatures
	9,  // 18: tokenization.ChatTemplateRequest.ChatTemplateKwargsEntry.value:type_name -> tokenization.Value
	9,  // 19: tokenization.ToolDescription.ToolEntry.value:type_name -> tokenization.Value
	9,  // 20: tokenization.Document.DocumentEntry.value:type_name -> tokenization.Value
	9,  // 21: tokenization.StructValue.FieldsEntry.value:type_name -> tokenization.Value
	16, // 22: tokenization.MultiModalFeatures.MmHashesEntry.value:type_name -> tokenization.StringList
	17, // 23: tokenization.MultiModalFeatures.MmPlaceholdersEntry.value:type_name -> tokenization.PlaceholderRangeList
	0,  // 24: tokenization.TokenizationService.Tokenize:input_type -> tokenization.TokenizeRequest
	3,  // 25: tokenization.TokenizationService.RenderChatTemplate:input_type -> tokenization.ChatTemplateRequest
	13, // 26: tokenization.TokenizationService.InitializeTokenizer:input_type -> tokenization.InitializeTokenizerRequest
	19, // 27: tokenization.TokenizationService.RenderChatCompletion:input_type -> tokenization.RenderChatCompletionRequest
	21, // 28: tokenization.TokenizationService.RenderCompletion:input_type -> tokenization.RenderCompletionRequest
	1,  // 29: tokenization.TokenizationService.Tokenize:output_type -> tokenization.TokenizeResponse
	12, // 30: tokenization.TokenizationService.RenderChatTemplate:output_type -> tokenization.ChatTemplateResponse
	14, // 31: tokenization.TokenizationService.InitializeTokenizer:output_type -> tokenization.InitializeTokenizerResponse
	20, // 32: tokenization.TokenizationService.RenderChatCompletion:output_type -> tokenization.RenderChatCompletionResponse
	22, // 33: tokenization.TokenizationService.RenderCompletion:output_type -> tokenization.RenderCompletionResponse
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_tokenizerpb_tokenizer_proto_init() }
func file_api_tokenizerpb_tokenizer_proto_init() {
	if File_api_tokenizerpb_tokenizer_proto != nil {
		return
	}
	file_api_tokenizerpb_tokenizer_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_tokenizerpb_tokenizer_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_tokenizerpb_tokenizer_proto_msgTypes[9].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_StructValue)(nil),
	}
	file_api_tokenizerpb_tokenizer_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tokenizerpb_tokenizer_proto_rawDesc), len(file_api_tokenizerpb_tokenizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tokenizerpb_tokenizer_proto_goTypes,
		DependencyIndexes: file_api_tokenizerpb_tokenizer_proto_depIdxs,
		MessageInfos:      file_api_tokenizerpb_tokenizer_proto_msgTypes,
	}.Build()
	File_api_tokenizerpb_tokenizer_proto = out.File
	file_api_tokenizerpb_tokenizer_proto_goTypes = nil
	file_api_tokenizerpb_tokenizer_proto_depIdxs = nil
}
