// Copyright 2025 The llm-d Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: api/tokenizerpb/tokenizer.proto

package tokenizerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenizationService_Tokenize_FullMethodName             = "/tokenization.TokenizationService/Tokenize"
	TokenizationService_RenderChatTemplate_FullMethodName   = "/tokenization.TokenizationService/RenderChatTemplate"
	TokenizationService_InitializeTokenizer_FullMethodName  = "/tokenization.TokenizationService/InitializeTokenizer"
	TokenizationService_RenderChatCompletion_FullMethodName = "/tokenization.TokenizationService/RenderChatCompletion"
	TokenizationService_RenderCompletion_FullMethodName     = "/tokenization.TokenizationService/RenderCompletion"
)

// TokenizationServiceClient is the client API for TokenizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenizationService defines the gRPC service for tokenization
type TokenizationServiceClient interface {
	// Tokenize converts a text input to token IDs
	Tokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResponse, error)
	// Deprecated: use RenderChatCompletion instead.
	RenderChatTemplate(ctx context.Context, in *ChatTemplateRequest, opts ...grpc.CallOption) (*ChatTemplateResponse, error)
	// InitializeTokenizer initializes the tokenizer for a specific model
	InitializeTokenizer(ctx context.Context, in *InitializeTokenizerRequest, opts ...grpc.CallOption) (*InitializeTokenizerResponse, error)
	// RenderChatCompletion renders an OpenAI chat completion request via OpenAIServingRender,
	// returning token IDs and multimodal features as a GenerateRequest-compatible response
	RenderChatCompletion(ctx context.Context, in *RenderChatCompletionRequest, opts ...grpc.CallOption) (*RenderChatCompletionResponse, error)
	// RenderCompletion renders an OpenAI completion request via OpenAIServingRender,
	// returning the rendered output for the given prompt
	RenderCompletion(ctx context.Context, in *RenderCompletionRequest, opts ...grpc.CallOption) (*RenderCompletionResponse, error)
}

type tokenizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenizationServiceClient(cc grpc.ClientConnInterface) TokenizationServiceClient {
	return &tokenizationServiceClient{cc}
}

func (c *tokenizationServiceClient) Tokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenizeResponse)
	err := c.cc.Invoke(ctx, TokenizationService_Tokenize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) RenderChatTemplate(ctx context.Context, in *ChatTemplateRequest, opts ...grpc.CallOption) (*ChatTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatTemplateResponse)
	err := c.cc.Invoke(ctx, TokenizationService_RenderChatTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) InitializeTokenizer(ctx context.Context, in *InitializeTokenizerRequest, opts ...grpc.CallOption) (*InitializeTokenizerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeTokenizerResponse)
	err := c.cc.Invoke(ctx, TokenizationService_InitializeTokenizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) RenderChatCompletion(ctx context.Context, in *RenderChatCompletionRequest, opts ...grpc.CallOption) (*RenderChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderChatCompletionResponse)
	err := c.cc.Invoke(ctx, TokenizationService_RenderChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) RenderCompletion(ctx context.Context, in *RenderCompletionRequest, opts ...grpc.CallOption) (*RenderCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderCompletionResponse)
	err := c.cc.Invoke(ctx, TokenizationService_RenderCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenizationServiceServer is the server API for TokenizationService service.
// All implementations must embed UnimplementedTokenizationServiceServer
// for forward compatibility.
//
// TokenizationService defines the gRPC service for tokenization
type TokenizationServiceServer interface {
	// Tokenize converts a text input to token IDs
	Tokenize(context.Context, *TokenizeRequest) (*TokenizeResponse, error)
	// Deprecated: use RenderChatCompletion instead.
	RenderChatTemplate(context.Context, *ChatTemplateRequest) (*ChatTemplateResponse, error)
	// InitializeTokenizer initializes the tokenizer for a specific model
	InitializeTokenizer(context.Context, *InitializeTokenizerRequest) (*InitializeTokenizerResponse, error)
	// RenderChatCompletion renders an OpenAI chat completion request via OpenAIServingRender,
	// returning token IDs and multimodal features as a GenerateRequest-compatible response
	RenderChatCompletion(context.Context, *RenderChatCompletionRequest) (*RenderChatCompletionResponse, error)
	// RenderCompletion renders an OpenAI completion request via OpenAIServingRender,
	// returning the rendered output for the given prompt
	RenderCompletion(context.Context, *RenderCompletionRequest) (*RenderCompletionResponse, error)
	mustEmbedUnimplementedTokenizationServiceServer()
}

// UnimplementedTokenizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenizationServiceServer struct{}

func (UnimplementedTokenizationServiceServer) Tokenize(context.Context, *TokenizeRequest) (*TokenizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tokenize not implemented")
}
func (UnimplementedTokenizationServiceServer) RenderChatTemplate(context.Context, *ChatTemplateRequest) (*ChatTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderChatTemplate not implemented")
}
func (UnimplementedTokenizationServiceServer) InitializeTokenizer(context.Context, *InitializeTokenizerRequest) (*InitializeTokenizerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeTokenizer not implemented")
}
func (UnimplementedTokenizationServiceServer) RenderChatCompletion(context.Context, *RenderChatCompletionRequest) (*RenderChatCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderChatCompletion not implemented")
}
func (UnimplementedTokenizationServiceServer) RenderCompletion(context.Context, *RenderCompletionRequest) (*RenderCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderCompletion not implemented")
}
func (UnimplementedTokenizationServiceServer) mustEmbedUnimplementedTokenizationServiceServer() {}
func (UnimplementedTokenizationServiceServer) testEmbeddedByValue()                             {}

// UnsafeTokenizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenizationServiceServer will
// result in compilation errors.
type UnsafeTokenizationServiceServer interface {
	mustEmbedUnimplementedTokenizationServiceServer()
}

func RegisterTokenizationServiceServer(s grpc.ServiceRegistrar, srv TokenizationServiceServer) {
	// If the following call panics, it indicates UnimplementedTokenizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenizationService_ServiceDesc, srv)
}

func _TokenizationService_Tokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).Tokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_Tokenize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).Tokenize(ctx, req.(*TokenizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_RenderChatTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).RenderChatTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_RenderChatTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).RenderChatTemplate(ctx, req.(*ChatTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_InitializeTokenizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeTokenizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).InitializeTokenizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_InitializeTokenizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).InitializeTokenizer(ctx, req.(*InitializeTokenizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_RenderChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).RenderChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_RenderChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).RenderChatCompletion(ctx, req.(*RenderChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_RenderCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).RenderCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_RenderCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).RenderCompletion(ctx, req.(*RenderCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenizationService_ServiceDesc is the grpc.ServiceDesc for TokenizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenization.TokenizationService",
	HandlerType: (*TokenizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tokenize",
			Handler:    _TokenizationService_Tokenize_Handler,
		},
		{
			MethodName: "RenderChatTemplate",
			Handler:    _TokenizationService_RenderChatTemplate_Handler,
		},
		{
			MethodName: "InitializeTokenizer",
			Handler:    _TokenizationService_InitializeTokenizer_Handler,
		},
		{
			MethodName: "RenderChatCompletion",
			Handler:    _TokenizationService_RenderChatCompletion_Handler,
		},
		{
			MethodName: "RenderCompletion",
			Handler:    _TokenizationService_RenderCompletion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tokenizerpb/tokenizer.proto",
}
