// Copyright 2025 The llm-d Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/indexerpb/indexer.proto

package indexerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPodScores
type GetPodScoresRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prompt         string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ModelName      string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	PodIdentifiers []string               `protobuf:"bytes,3,rep,name=pod_identifiers,json=podIdentifiers,proto3" json:"pod_identifiers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPodScoresRequest) Reset() {
	*x = GetPodScoresRequest{}
	mi := &file_api_indexerpb_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodScoresRequest) ProtoMessage() {}

func (x *GetPodScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_indexerpb_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodScoresRequest.ProtoReflect.Descriptor instead.
func (*GetPodScoresRequest) Descriptor() ([]byte, []int) {
	return file_api_indexerpb_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *GetPodScoresRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GetPodScoresRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetPodScoresRequest) GetPodIdentifiers() []string {
	if x != nil {
		return x.PodIdentifiers
	}
	return nil
}

type GetPodScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*PodScore            `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodScoresResponse) Reset() {
	*x = GetPodScoresResponse{}
	mi := &file_api_indexerpb_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodScoresResponse) ProtoMessage() {}

func (x *GetPodScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_indexerpb_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodScoresResponse.ProtoReflect.Descriptor instead.
func (*GetPodScoresResponse) Descriptor() ([]byte, []int) {
	return file_api_indexerpb_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *GetPodScoresResponse) GetScores() []*PodScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type PodScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           string                 `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodScore) Reset() {
	*x = PodScore{}
	mi := &file_api_indexerpb_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodScore) ProtoMessage() {}

func (x *PodScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_indexerpb_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodScore.ProtoReflect.Descriptor instead.
func (*PodScore) Descriptor() ([]byte, []int) {
	return file_api_indexerpb_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *PodScore) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *PodScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_indexerpb_indexer_proto protoreflect.FileDescriptor

const file_api_indexerpb_indexer_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/indexerpb/indexer.proto\x12\n" +
	"indexer.v1\"u\n" +
	"\x13GetPodScoresRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12'\n" +
	"\x0fpod_identifiers\x18\x03 \x03(\tR\x0epodIdentifiers\"D\n" +
	"\x14GetPodScoresResponse\x12,\n" +
	"\x06scores\x18\x01 \x03(\v2\x14.indexer.v1.PodScoreR\x06scores\"2\n" +
	"\bPodScore\x12\x10\n" +
	"\x03pod\x18\x01 \x01(\tR\x03pod\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score2e\n" +
	"\x0eIndexerService\x12S\n" +
	"\fGetPodScores\x12\x1f.indexer.v1.GetPodScoresRequest\x1a .indexer.v1.GetPodScoresResponse\"\x00B9Z7github.com/llm-d/llm-d-kv-cache/api/indexerpb;indexerpbb\x06proto3"

var (
	file_api_indexerpb_indexer_proto_rawDescOnce sync.Once
	file_api_indexerpb_indexer_proto_rawDescData []byte
)

func file_api_indexerpb_indexer_proto_rawDescGZIP() []byte {
	file_api_indexerpb_indexer_proto_rawDescOnce.Do(func() {
		file_api_indexerpb_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_indexerpb_indexer_proto_rawDesc), len(file_api_indexerpb_indexer_proto_rawDesc)))
	})
	return file_api_indexerpb_indexer_proto_rawDescData
}

var file_api_indexerpb_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_indexerpb_indexer_proto_goTypes = []any{
	(*GetPodScoresRequest)(nil),  // 0: indexer.v1.GetPodScoresRequest
	(*GetPodScoresResponse)(nil), // 1: indexer.v1.GetPodScoresResponse
	(*PodScore)(nil),             // 2: indexer.v1.PodScore
}
var file_api_indexerpb_indexer_proto_depIdxs = []int32{
	2, // 0: indexer.v1.GetPodScoresResponse.scores:type_name -> indexer.v1.PodScore
	0, // 1: indexer.v1.IndexerService.GetPodScores:input_type -> indexer.v1.GetPodScoresRequest
	1, // 2: indexer.v1.IndexerService.GetPodScores:output_type -> indexer.v1.GetPodScoresResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_indexerpb_indexer_proto_init() }
func file_api_indexerpb_indexer_proto_init() {
	if File_api_indexerpb_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_indexerpb_indexer_proto_rawDesc), len(file_api_indexerpb_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_indexerpb_indexer_proto_goTypes,
		DependencyIndexes: file_api_indexerpb_indexer_proto_depIdxs,
		MessageInfos:      file_api_indexerpb_indexer_proto_msgTypes,
	}.Build()
	File_api_indexerpb_indexer_proto = out.File
	file_api_indexerpb_indexer_proto_goTypes = nil
	file_api_indexerpb_indexer_proto_depIdxs = nil
}
